[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart_contract = "6HF7SL2ydXxthwKgFmw5ELh9QzkgrTav7AWEuKcCqh5"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
